-- CREATE DATABASE CHUNGKHOAN;

-- CREATE TABLE LENHDAT (
--     ID int NOT NULL IDENTITY(1,1),
--     MACP varchar(20),
--     NGAYDAT datetime DEFAULT CURRENT_TIMESTAMP,
--     LOAIGD varchar(1),
--     LOAILENH varchar(10),
--     SOLUONG INT,
--     GIADAT FLOAT,
--     TRANGTHAILENH varchar(30)
-- );

-- CREATE TABLE LENHKHOP(
--     IDKHOP int NOT NULL IDENTITY(1,1),
--     NGAYKHOP datetime DEFAULT CURRENT_TIMESTAMP,
--     SOLUONGKHOP int,
--     GIAKHOP float,
--     IDLENHDAT int
-- )

-- INSERT INTO dbo.LENHDAT (MACP, LOAIGD, LOAILENH, SOLUONG, GIADAT, TRANGTHAILENH)
-- VALUES ('FLC', 'M', 'LO', 1000, 9500, 'DANG CHO');

-- ALTER TABLE LENHDAT
-- ADD CONSTRAINT PK_LD PRIMARY KEY (ID);

-- ALTER TABLE LENHKHOP
-- ADD CONSTRAINT FK_LK FOREIGN KEY (IDLENHDAT) REFERENCES LENHDAT(ID);

-- INSERT INTO dbo.LENHDAT (MACP, LOAIGD, LOAILENH, SOLUONG, GIADAT, TRANGTHAILENH)
-- VALUES ('FLC', 'M', 'LO', 1000, 8900, 'CHUA KHOP');

DELETE FROM LENHKHOP;
DELETE FROM LENHDAT;