SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TRIGGER [dbo].[AFTER_KHOPLENH]
ON [dbo].[LENHKHOP]
AFTER INSERT, UPDATE
AS
BEGIN

    DECLARE @macp varchar(20);
    SELECT @macp = a.MACP FROM LENHDAT a, INSERTED b WHERE a.ID = b.IDLENHDAT

    UPDATE dbo.BANGTRUCTUYEN 
	SET GiaKhopLenh = (SELECT GIAKHOP FROM INSERTED),
		KLKhopLenh = (SELECT SOLUONGKHOP FROM INSERTED),
        TongKL = TongKL + (SELECT SOLUONGKHOP FROM INSERTED)
	WHERE dbo.BANGTRUCTUYEN.MACP = @macp
    
END
GO
ALTER TABLE [dbo].[LENHKHOP] ENABLE TRIGGER [AFTER_KHOPLENH]
GO
