SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TRIGGER [dbo].[AFTER_DATLENH]
ON [dbo].[LENHDAT]
AFTER INSERT, UPDATE
AS
BEGIN

    DECLARE @macp varchar(20)
    SELECT @macp = MACP FROM INSERTED
     PRINT('First Statement: ' + @macp)

    EXEC PREC_SET_BENBAN_BGT @macp = @macp
    EXEC PREC_SET_BENMUA_BGT @macp = @macp

END
GO
ALTER TABLE [dbo].[LENHDAT] ENABLE TRIGGER [AFTER_DATLENH]
GO
